name: unique_list
description: An implementation of List that enforces all elements be unique.
version: 1.0.0
homepage: https://github.com/james-alex/unique_list

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  collection: ^1.15.0
  pedantic: ^1.11.0
  test: ^1.16.8
